Use curl instead of openssl
On my box, and maybe on travis VM, SSLv3 is no supported anymore by openssl
(1.0.1j)

diff --git a/test b/test
--- a/test
+++ b/test
@@ -5,14 +5,11 @@ test_host="127.0.0.1"
 
 # from https://raymii.org/s/articles/Check_servers_for_the_Poodle_bug.html
 
-echo | timeout 3 openssl s_client -connect ${test_host}:${test_port} >/dev/null 2>&1
-if [[ $? != 0 ]]; then
-	echo "UNKNOWN: ${test_host} timeout or connection error"
+# Check for exit code 35: SSL connect error. The SSL handshaking failed.
+curl -s -3 --insecure https://${test_host}:${test_port}  -o /dev/null
+if [[ $? != 35 ]]; then
+    echo "FAIL: ${test_host} vulnerable; sslv3 connection accepted"
+    exit -1
 else
-	echo | openssl s_client -connect ${test_host}:${test_port} -ssl3 2>&1 | grep -q 'Protocol  : SSLv3' && {
-        echo "FAIL: ${test_host} vulnerable; sslv3 connection accepted"
-        exit -1
-    } || {
-		echo "OK: ${test_host} Not vulnerable"
-    }
+    echo "OK: ${test_host} Not vulnerable"
 fi
